const olympicData = [
  {
    "ID": 1,
    "Name": "A Dijiang",
    "Sex": "M",
    "Age": 24,
    "Height": 180,
    "Weight": 80,
    "Team": "China",
    "NOC": "CHN",
    "Games": "1992 Summer",
    "Year": 1992,
    "Season": "Summer",
    "City": "Barcelona",
    "Sport": "Basketball",
    "Event": "Basketball Men's Basketball",
    "Medal": null
  },
  {
    "ID": 2,
    "Name": "A Lamusi",
    "Sex": "M",
    "Age": 23,
    "Height": 170,
    "Weight": 60,
    "Team": "China",
    "NOC": "CHN",
    "Games": "2012 Summer",
    "Year": 2012,
    "Season": "Summer",
    "City": "London",
    "Sport": "Judo",
    "Event": "Judo Men's Extra-Lightweight",
    "Medal": null
  },
  {
    "ID": 3,
    "Name": "Gunnar Nielsen Aaby",
    "Sex": "M",
    "Age": 24,
    "Height": null,
    "Weight": null,
    "Team": "Denmark",
    "NOC": "DEN",
    "Games": "1920 Summer",
    "Year": 1920,
    "Season": "Summer",
    "City": "Antwerpen",
    "Sport": "Football",
    "Event": "Football Men's Football",
    "Medal": null
  },
  {
    "ID": 4,
    "Name": "Edgar Lindenau Aabye",
    "Sex": "M",
    "Age": 34,
    "Height": null,
    "Weight": null,
    "Team": "Denmark/Sweden",
    "NOC": "DEN",
    "Games": "1900 Summer",
    "Year": 1900,
    "Season": "Summer",
    "City": "Paris",
    "Sport": "Tug-Of-War",
    "Event": "Tug-Of-War Men's Tug-Of-War",
    "Medal": "Gold"
  },
  {
    "ID": 5,
    "Name": "Christine Jacoba Aaftink",
    "Sex": "F",
    "Age": 21,
    "Height": 185,
    "Weight": 82,
    "Team": "Netherlands",
    "NOC": "NED",
    "Games": "1988 Winter",
    "Year": 1988,
    "Season": "Winter",
    "City": "Calgary",
    "Sport": "Speed Skating",
    "Event": "Speed Skating Women's 500 metres",
    "Medal": null
  },
  {
    "ID": 5,
    "Name": "Christine Jacoba Aaftink",
    "Sex": "F",
    "Age": 21,
    "Height": 185,
    "Weight": 82,
    "Team": "Netherlands",
    "NOC": "NED",
    "Games": "1988 Winter",
    "Year": 1988,
    "Season": "Winter",
    "City": "Calgary",
    "Sport": "Speed Skating",
    "Event": "Speed Skating Women's 1,000 metres",
    "Medal": null
  },
  {
    "ID": 5,
    "Name": "Christine Jacoba Aaftink",
    "Sex": "F",
    "Age": 25,
    "Height": 185,
    "Weight": 82,
    "Team": "Netherlands",
    "NOC": "NED",
    "Games": "1992 Winter",
    "Year": 1992,
    "Season": "Winter",
    "City": "Albertville",
    "Sport": "Speed Skating",
    "Event": "Speed Skating Women's 500 metres",
    "Medal": null
  },
  {
    "ID": 5,
    "Name": "Christine Jacoba Aaftink",
    "Sex": "F",
    "Age": 25,
    "Height": 185,
    "Weight": 82,
    "Team": "Netherlands",
    "NOC": "NED",
    "Games": "1992 Winter",
    "Year": 1992,
    "Season": "Winter",
    "City": "Albertville",
    "Sport": "Speed Skating",
    "Event": "Speed Skating Women's 1,000 metres",
    "Medal": null
  },
  {
    "ID": 5,
    "Name": "Christine Jacoba Aaftink",
    "Sex": "F",
    "Age": 27,
    "Height": 185,
    "Weight": 82,
    "Team": "Netherlands",
    "NOC": "NED",
    "Games": "1994 Winter",
    "Year": 1994,
    "Season": "Winter",
    "City": "Lillehammer",
    "Sport": "Speed Skating",
    "Event": "Speed Skating Women's 500 metres",
    "Medal": null
  },
  {
    "ID": 5,
    "Name": "Christine Jacoba Aaftink",
    "Sex": "F",
    "Age": 27,
    "Height": 185,
    "Weight": 82,
    "Team": "Netherlands",
    "NOC": "NED",
    "Games": "1994 Winter",
    "Year": 1994,
    "Season": "Winter",
    "City": "Lillehammer",
    "Sport": "Speed Skating",
    "Event": "Speed Skating Women's 1,000 metres",
    "Medal": null
  },
  {
    "ID": 6,
    "Name": "Per Knut Aaland",
    "Sex": "M",
    "Age": 31,
    "Height": 188,
    "Weight": 75,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1992 Winter",
    "Year": 1992,
    "Season": "Winter",
    "City": "Albertville",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 10 kilometres",
    "Medal": null
  },
  {
    "ID": 6,
    "Name": "Per Knut Aaland",
    "Sex": "M",
    "Age": 31,
    "Height": 188,
    "Weight": 75,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1992 Winter",
    "Year": 1992,
    "Season": "Winter",
    "City": "Albertville",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 50 kilometres",
    "Medal": null
  },
  {
    "ID": 6,
    "Name": "Per Knut Aaland",
    "Sex": "M",
    "Age": 31,
    "Height": 188,
    "Weight": 75,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1992 Winter",
    "Year": 1992,
    "Season": "Winter",
    "City": "Albertville",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 10/15 kilometres Pursuit",
    "Medal": null
  },
  {
    "ID": 6,
    "Name": "Per Knut Aaland",
    "Sex": "M",
    "Age": 31,
    "Height": 188,
    "Weight": 75,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1992 Winter",
    "Year": 1992,
    "Season": "Winter",
    "City": "Albertville",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 4 x 10 kilometres Relay",
    "Medal": null
  },
  {
    "ID": 6,
    "Name": "Per Knut Aaland",
    "Sex": "M",
    "Age": 33,
    "Height": 188,
    "Weight": 75,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1994 Winter",
    "Year": 1994,
    "Season": "Winter",
    "City": "Lillehammer",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 10 kilometres",
    "Medal": null
  },
  {
    "ID": 6,
    "Name": "Per Knut Aaland",
    "Sex": "M",
    "Age": 33,
    "Height": 188,
    "Weight": 75,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1994 Winter",
    "Year": 1994,
    "Season": "Winter",
    "City": "Lillehammer",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 30 kilometres",
    "Medal": null
  },
  {
    "ID": 6,
    "Name": "Per Knut Aaland",
    "Sex": "M",
    "Age": 33,
    "Height": 188,
    "Weight": 75,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1994 Winter",
    "Year": 1994,
    "Season": "Winter",
    "City": "Lillehammer",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 10/15 kilometres Pursuit",
    "Medal": null
  },
  {
    "ID": 6,
    "Name": "Per Knut Aaland",
    "Sex": "M",
    "Age": 33,
    "Height": 188,
    "Weight": 75,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1994 Winter",
    "Year": 1994,
    "Season": "Winter",
    "City": "Lillehammer",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 4 x 10 kilometres Relay",
    "Medal": null
  },
  {
    "ID": 7,
    "Name": "John Aalberg",
    "Sex": "M",
    "Age": 31,
    "Height": 183,
    "Weight": 72,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1992 Winter",
    "Year": 1992,
    "Season": "Winter",
    "City": "Albertville",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 10 kilometres",
    "Medal": null
  },
  {
    "ID": 7,
    "Name": "John Aalberg",
    "Sex": "M",
    "Age": 31,
    "Height": 183,
    "Weight": 72,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1992 Winter",
    "Year": 1992,
    "Season": "Winter",
    "City": "Albertville",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 50 kilometres",
    "Medal": null
  },
  {
    "ID": 7,
    "Name": "John Aalberg",
    "Sex": "M",
    "Age": 31,
    "Height": 183,
    "Weight": 72,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1992 Winter",
    "Year": 1992,
    "Season": "Winter",
    "City": "Albertville",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 10/15 kilometres Pursuit",
    "Medal": null
  },
  {
    "ID": 7,
    "Name": "John Aalberg",
    "Sex": "M",
    "Age": 31,
    "Height": 183,
    "Weight": 72,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1992 Winter",
    "Year": 1992,
    "Season": "Winter",
    "City": "Albertville",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 4 x 10 kilometres Relay",
    "Medal": null
  },
  {
    "ID": 7,
    "Name": "John Aalberg",
    "Sex": "M",
    "Age": 33,
    "Height": 183,
    "Weight": 72,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1994 Winter",
    "Year": 1994,
    "Season": "Winter",
    "City": "Lillehammer",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 10 kilometres",
    "Medal": null
  },
  {
    "ID": 7,
    "Name": "John Aalberg",
    "Sex": "M",
    "Age": 33,
    "Height": 183,
    "Weight": 72,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1994 Winter",
    "Year": 1994,
    "Season": "Winter",
    "City": "Lillehammer",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 30 kilometres",
    "Medal": null
  },
  {
    "ID": 7,
    "Name": "John Aalberg",
    "Sex": "M",
    "Age": 33,
    "Height": 183,
    "Weight": 72,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1994 Winter",
    "Year": 1994,
    "Season": "Winter",
    "City": "Lillehammer",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 10/15 kilometres Pursuit",
    "Medal": null
  },
  {
    "ID": 7,
    "Name": "John Aalberg",
    "Sex": "M",
    "Age": 33,
    "Height": 183,
    "Weight": 72,
    "Team": "United States",
    "NOC": "USA",
    "Games": "1994 Winter",
    "Year": 1994,
    "Season": "Winter",
    "City": "Lillehammer",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 4 x 10 kilometres Relay",
    "Medal": null
  },
  {
    "ID": 8,
    "Name": "Cornelia \"Cor\" Aalten (-Strannood)",
    "Sex": "F",
    "Age": 18,
    "Height": 168,
    "Weight": null,
    "Team": "Netherlands",
    "NOC": "NED",
    "Games": "1932 Summer",
    "Year": 1932,
    "Season": "Summer",
    "City": "Los Angeles",
    "Sport": "Athletics",
    "Event": "Athletics Women's 100 metres",
    "Medal": null
  },
  {
    "ID": 8,
    "Name": "Cornelia \"Cor\" Aalten (-Strannood)",
    "Sex": "F",
    "Age": 18,
    "Height": 168,
    "Weight": null,
    "Team": "Netherlands",
    "NOC": "NED",
    "Games": "1932 Summer",
    "Year": 1932,
    "Season": "Summer",
    "City": "Los Angeles",
    "Sport": "Athletics",
    "Event": "Athletics Women's 4 x 100 metres Relay",
    "Medal": null
  },
  {
    "ID": 9,
    "Name": "Antti Sami Aalto",
    "Sex": "M",
    "Age": 26,
    "Height": 186,
    "Weight": 96,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "2002 Winter",
    "Year": 2002,
    "Season": "Winter",
    "City": "Salt Lake City",
    "Sport": "Ice Hockey",
    "Event": "Ice Hockey Men's Ice Hockey",
    "Medal": null
  },
  {
    "ID": 10,
    "Name": "Einar Ferdinand \"Einari\" Aalto",
    "Sex": "M",
    "Age": 26,
    "Height": null,
    "Weight": null,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1952 Summer",
    "Year": 1952,
    "Season": "Summer",
    "City": "Helsinki",
    "Sport": "Swimming",
    "Event": "Swimming Men's 400 metres Freestyle",
    "Medal": null
  },
  {
    "ID": 11,
    "Name": "Jorma Ilmari Aalto",
    "Sex": "M",
    "Age": 22,
    "Height": 182,
    "Weight": 76.5,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1980 Winter",
    "Year": 1980,
    "Season": "Winter",
    "City": "Lake Placid",
    "Sport": "Cross Country Skiing",
    "Event": "Cross Country Skiing Men's 30 kilometres",
    "Medal": null
  },
  {
    "ID": 12,
    "Name": "Jyri Tapani Aalto",
    "Sex": "M",
    "Age": 31,
    "Height": 172,
    "Weight": 70,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "2000 Summer",
    "Year": 2000,
    "Season": "Summer",
    "City": "Sydney",
    "Sport": "Badminton",
    "Event": "Badminton Men's Singles",
    "Medal": null
  },
  {
    "ID": 13,
    "Name": "Minna Maarit Aalto",
    "Sex": "F",
    "Age": 30,
    "Height": 159,
    "Weight": 55.5,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1996 Summer",
    "Year": 1996,
    "Season": "Summer",
    "City": "Atlanta",
    "Sport": "Sailing",
    "Event": "Sailing Women's Windsurfer",
    "Medal": null
  },
  {
    "ID": 13,
    "Name": "Minna Maarit Aalto",
    "Sex": "F",
    "Age": 34,
    "Height": 159,
    "Weight": 55.5,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "2000 Summer",
    "Year": 2000,
    "Season": "Summer",
    "City": "Sydney",
    "Sport": "Sailing",
    "Event": "Sailing Women's Windsurfer",
    "Medal": null
  },
  {
    "ID": 14,
    "Name": "Pirjo Hannele Aalto (Mattila-)",
    "Sex": "F",
    "Age": 32,
    "Height": 171,
    "Weight": 65,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1994 Winter",
    "Year": 1994,
    "Season": "Winter",
    "City": "Lillehammer",
    "Sport": "Biathlon",
    "Event": "Biathlon Women's 7.5 kilometres Sprint",
    "Medal": null
  },
  {
    "ID": 15,
    "Name": "Arvo Ossian Aaltonen",
    "Sex": "M",
    "Age": 22,
    "Height": null,
    "Weight": null,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1912 Summer",
    "Year": 1912,
    "Season": "Summer",
    "City": "Stockholm",
    "Sport": "Swimming",
    "Event": "Swimming Men's 200 metres Breaststroke",
    "Medal": null
  },
  {
    "ID": 15,
    "Name": "Arvo Ossian Aaltonen",
    "Sex": "M",
    "Age": 22,
    "Height": null,
    "Weight": null,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1912 Summer",
    "Year": 1912,
    "Season": "Summer",
    "City": "Stockholm",
    "Sport": "Swimming",
    "Event": "Swimming Men's 400 metres Breaststroke",
    "Medal": null
  },
  {
    "ID": 15,
    "Name": "Arvo Ossian Aaltonen",
    "Sex": "M",
    "Age": 30,
    "Height": null,
    "Weight": null,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1920 Summer",
    "Year": 1920,
    "Season": "Summer",
    "City": "Antwerpen",
    "Sport": "Swimming",
    "Event": "Swimming Men's 200 metres Breaststroke",
    "Medal": "Bronze"
  },
  {
    "ID": 15,
    "Name": "Arvo Ossian Aaltonen",
    "Sex": "M",
    "Age": 30,
    "Height": null,
    "Weight": null,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1920 Summer",
    "Year": 1920,
    "Season": "Summer",
    "City": "Antwerpen",
    "Sport": "Swimming",
    "Event": "Swimming Men's 400 metres Breaststroke",
    "Medal": "Bronze"
  },
  {
    "ID": 15,
    "Name": "Arvo Ossian Aaltonen",
    "Sex": "M",
    "Age": 34,
    "Height": null,
    "Weight": null,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1924 Summer",
    "Year": 1924,
    "Season": "Summer",
    "City": "Paris",
    "Sport": "Swimming",
    "Event": "Swimming Men's 200 metres Breaststroke",
    "Medal": null
  },
  {
    "ID": 16,
    "Name": "Juhamatti Tapio Aaltonen",
    "Sex": "M",
    "Age": 28,
    "Height": 184,
    "Weight": 85,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "2014 Winter",
    "Year": 2014,
    "Season": "Winter",
    "City": "Sochi",
    "Sport": "Ice Hockey",
    "Event": "Ice Hockey Men's Ice Hockey",
    "Medal": "Bronze"
  },
  {
    "ID": 17,
    "Name": "Paavo Johannes Aaltonen",
    "Sex": "M",
    "Age": 28,
    "Height": 175,
    "Weight": 64,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1948 Summer",
    "Year": 1948,
    "Season": "Summer",
    "City": "London",
    "Sport": "Gymnastics",
    "Event": "Gymnastics Men's Individual All-Around",
    "Medal": "Bronze"
  },
  {
    "ID": 17,
    "Name": "Paavo Johannes Aaltonen",
    "Sex": "M",
    "Age": 28,
    "Height": 175,
    "Weight": 64,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1948 Summer",
    "Year": 1948,
    "Season": "Summer",
    "City": "London",
    "Sport": "Gymnastics",
    "Event": "Gymnastics Men's Team All-Around",
    "Medal": "Gold"
  },
  {
    "ID": 17,
    "Name": "Paavo Johannes Aaltonen",
    "Sex": "M",
    "Age": 28,
    "Height": 175,
    "Weight": 64,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1948 Summer",
    "Year": 1948,
    "Season": "Summer",
    "City": "London",
    "Sport": "Gymnastics",
    "Event": "Gymnastics Men's Floor Exercise",
    "Medal": null
  },
  {
    "ID": 17,
    "Name": "Paavo Johannes Aaltonen",
    "Sex": "M",
    "Age": 28,
    "Height": 175,
    "Weight": 64,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1948 Summer",
    "Year": 1948,
    "Season": "Summer",
    "City": "London",
    "Sport": "Gymnastics",
    "Event": "Gymnastics Men's Horse Vault",
    "Medal": "Gold"
  },
  {
    "ID": 17,
    "Name": "Paavo Johannes Aaltonen",
    "Sex": "M",
    "Age": 28,
    "Height": 175,
    "Weight": 64,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1948 Summer",
    "Year": 1948,
    "Season": "Summer",
    "City": "London",
    "Sport": "Gymnastics",
    "Event": "Gymnastics Men's Parallel Bars",
    "Medal": null
  },
  {
    "ID": 17,
    "Name": "Paavo Johannes Aaltonen",
    "Sex": "M",
    "Age": 28,
    "Height": 175,
    "Weight": 64,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1948 Summer",
    "Year": 1948,
    "Season": "Summer",
    "City": "London",
    "Sport": "Gymnastics",
    "Event": "Gymnastics Men's Horizontal Bar",
    "Medal": null
  },
  {
    "ID": 17,
    "Name": "Paavo Johannes Aaltonen",
    "Sex": "M",
    "Age": 28,
    "Height": 175,
    "Weight": 64,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1948 Summer",
    "Year": 1948,
    "Season": "Summer",
    "City": "London",
    "Sport": "Gymnastics",
    "Event": "Gymnastics Men's Rings",
    "Medal": null
  },
  {
    "ID": 17,
    "Name": "Paavo Johannes Aaltonen",
    "Sex": "M",
    "Age": 28,
    "Height": 175,
    "Weight": 64,
    "Team": "Finland",
    "NOC": "FIN",
    "Games": "1948 Summer",
    "Year": 1948,
    "Season": "Summer",
    "City": "London",
    "Sport": "Gymnastics",
    "Event": "Gymnastics Men's Pommelled Horse",
    "Medal": "Gold"
  }
];
const countryArray = [
  [
    "China"
  ],
  [
    "Denmark"
  ],
  [
    "Denmark/Sweden"
  ],
  [
    "Finland"
  ],
  [
    "Netherlands"
  ],
  [
    "United States"
  ]
];
const eventArray = [
  [
    "Athletics"
  ],
  [
    "Badminton"
  ],
  [
    "Basketball"
  ],
  [
    "Biathlon"
  ],
  [
    "Cross Country Skiing"
  ],
  [
    "Football"
  ],
  [
    "Gymnastics"
  ],
  [
    "Ice Hockey"
  ],
  [
    "Judo"
  ],
  [
    "Sailing"
  ],
  [
    "Speed Skating"
  ],
  [
    "Swimming"
  ],
  [
    "Tug-Of-War"
  ]
];
