// NOC to ISO 3166-1 numeric mapping for Olympic data
// Generated from comprehensive research of Olympic NOC codes and ISO standards

var NOC_TO_ISO = {
  "AFG": "004",
  "AHO": "530",
  "ALB": "008",
  "ALG": "012",
  "AND": "020",
  "ANG": "024",
  "ANT": "028",
  "ANZ": "036",
  "ARG": "032",
  "ARM": "051",
  "ARU": "533",
  "ASA": "016",
  "AUS": "036",
  "AUT": "040",
  "AZE": "031",
  "BAH": "044",
  "BAN": "050",
  "BAR": "052",
  "BDI": "108",
  "BEL": "056",
  "BEN": "204",
  "BER": "060",
  "BHU": "064",
  "BIH": "070",
  "BIZ": "084",
  "BLR": "112",
  "BOH": "203",
  "BOL": "068",
  "BOT": "072",
  "BRA": "076",
  "BRN": "048",
  "BRU": "096",
  "BUL": "100",
  "BUR": "854",
  "CAF": "140",
  "CAM": "116",
  "CAN": "124",
  "CAY": "136",
  "CGO": "178",
  "CHA": "148",
  "CHI": "152",
  "CHN": "156",
  "CIV": "384",
  "CMR": "120",
  "COD": "180",
  "COK": "184",
  "COL": "170",
  "COM": "174",
  "CPV": "132",
  "CRC": "188",
  "CRO": "191",
  "CRT": "300",
  "CUB": "192",
  "CYP": "196",
  "CZE": "203",
  "DEN": "208",
  "DJI": "262",
  "DMA": "212",
  "DOM": "214",
  "ECU": "218",
  "EGY": "818",
  "ERI": "232",
  "ESA": "222",
  "ESP": "724",
  "EST": "233",
  "ETH": "231",
  "EUN": "643",
  "FIJ": "242",
  "FIN": "246",
  "FRA": "250",
  "FRG": "276",
  "FSM": "583",
  "GAB": "266",
  "GAM": "270",
  "GBR": "826",
  "GBS": "624",
  "GDR": "276",
  "GEO": "268",
  "GEQ": "226",
  "GER": "276",
  "GHA": "288",
  "GRE": "300",
  "GRN": "308",
  "GUA": "320",
  "GUI": "324",
  "GUM": "316",
  "GUY": "328",
  "HAI": "332",
  "HKG": "344",
  "HON": "340",
  "HUN": "348",
  "INA": "360",
  "IND": "356",
  "IOA": "998",
  "IRI": "364",
  "IRL": "372",
  "IRQ": "368",
  "ISL": "352",
  "ISR": "376",
  "ISV": "850",
  "ITA": "380",
  "IVB": "092",
  "JAM": "388",
  "JOR": "400",
  "JPN": "392",
  "KAZ": "398",
  "KEN": "404",
  "KGZ": "417",
  "KIR": "296",
  "KOR": "410",
  "KOS": "383",
  "KSA": "682",
  "KUW": "414",
  "LAO": "418",
  "LAT": "428",
  "LBA": "434",
  "LBR": "430",
  "LCA": "662",
  "LES": "426",
  "LIB": "422",
  "LIE": "438",
  "LTU": "440",
  "LUX": "442",
  "MAD": "450",
  "MAL": "458",
  "MAR": "504",
  "MAS": "458",
  "MAW": "454",
  "MDA": "498",
  "MDV": "462",
  "MEX": "484",
  "MGL": "496",
  "MHL": "584",
  "MKD": "807",
  "MLI": "466",
  "MLT": "470",
  "MNE": "499",
  "MON": "492",
  "MOZ": "508",
  "MRI": "480",
  "MTN": "478",
  "MYA": "104",
  "NAM": "516",
  "NBO": "458",
  "NCA": "558",
  "NED": "528",
  "NEP": "524",
  "NFL": "124",
  "NGR": "566",
  "NIG": "562",
  "NOR": "578",
  "NRU": "520",
  "NZL": "554",
  "OMA": "512",
  "PAK": "586",
  "PAN": "591",
  "PAR": "600",
  "PER": "604",
  "PHI": "608",
  "PLE": "275",
  "PLW": "585",
  "PNG": "598",
  "POL": "616",
  "POR": "620",
  "PRK": "408",
  "PUR": "630",
  "QAT": "634",
  "RHO": "716",
  "ROT": "997",
  "ROU": "642",
  "RSA": "710",
  "RUS": "643",
  "RWA": "646",
  "SAA": "276",
  "SAM": "882",
  "SCG": "688",
  "SEN": "686",
  "SEY": "690",
  "SIN": "702",
  "SKN": "659",
  "SLE": "694",
  "SLO": "705",
  "SMR": "674",
  "SOL": "090",
  "SOM": "706",
  "SRB": "688",
  "SRI": "144",
  "SSD": "728",
  "STP": "678",
  "SUD": "729",
  "SUI": "756",
  "SUR": "740",
  "SVK": "703",
  "SWE": "752",
  "SWZ": "748",
  "SYR": "760",
  "TAN": "834",
  "TCH": "203",
  "TGA": "776",
  "THA": "764",
  "TJK": "762",
  "TKM": "795",
  "TLS": "626",
  "TOG": "768",
  "TPE": "158",
  "TTO": "780",
  "TUN": "788",
  "TUR": "792",
  "TUV": "798",
  "UAE": "784",
  "UAR": "760",
  "UGA": "800",
  "UKR": "804",
  "UNK": "999",
  "URS": "643",
  "URU": "858",
  "USA": "840",
  "UZB": "860",
  "VAN": "548",
  "VEN": "862",
  "VIE": "704",
  "VIN": "670",
  "VNM": "704",
  "WIF": "780",
  "YAR": "887",
  "YEM": "887",
  "YMD": "887",
  "YUG": "688",
  "ZAM": "894",
  "ZIM": "716"
};

// Country names for NOC codes (from noc_regions.csv)
var NOC_TO_COUNTRY = {
  "AFG": "Afghanistan",
  "AHO": "Curacao",
  "ALB": "Albania",
  "ALG": "Algeria",
  "AND": "Andorra",
  "ANG": "Angola",
  "ANT": "Antigua",
  "ANZ": "Australia",
  "ARG": "Argentina",
  "ARM": "Armenia",
  "ARU": "Aruba",
  "ASA": "American Samoa",
  "AUS": "Australia",
  "AUT": "Austria",
  "AZE": "Azerbaijan",
  "BAH": "Bahamas",
  "BAN": "Bangladesh",
  "BAR": "Barbados",
  "BDI": "Burundi",
  "BEL": "Belgium",
  "BEN": "Benin",
  "BER": "Bermuda",
  "BHU": "Bhutan",
  "BIH": "Bosnia and Herzegovina",
  "BIZ": "Belize",
  "BLR": "Belarus",
  "BOH": "Czech Republic",
  "BOL": "Boliva",
  "BOT": "Botswana",
  "BRA": "Brazil",
  "BRN": "Bahrain",
  "BRU": "Brunei",
  "BUL": "Bulgaria",
  "BUR": "Burkina Faso",
  "CAF": "Central African Republic",
  "CAM": "Cambodia",
  "CAN": "Canada",
  "CAY": "Cayman Islands",
  "CGO": "Republic of Congo",
  "CHA": "Chad",
  "CHI": "Chile",
  "CHN": "China",
  "CIV": "Ivory Coast",
  "CMR": "Cameroon",
  "COD": "Democratic Republic of the Congo",
  "COK": "Cook Islands",
  "COL": "Colombia",
  "COM": "Comoros",
  "CPV": "Cape Verde",
  "CRC": "Costa Rica",
  "CRO": "Croatia",
  "CRT": "Greece",
  "CUB": "Cuba",
  "CYP": "Cyprus",
  "CZE": "Czech Republic",
  "DEN": "Denmark",
  "DJI": "Djibouti",
  "DMA": "Dominica",
  "DOM": "Dominican Republic",
  "ECU": "Ecuador",
  "EGY": "Egypt",
  "ERI": "Eritrea",
  "ESA": "El Salvador",
  "ESP": "Spain",
  "EST": "Estonia",
  "ETH": "Ethiopia",
  "EUN": "Russia",
  "FIJ": "Fiji",
  "FIN": "Finland",
  "FRA": "France",
  "FRG": "Germany",
  "FSM": "Micronesia",
  "GAB": "Gabon",
  "GAM": "Gambia",
  "GBR": "UK",
  "GBS": "Guinea-Bissau",
  "GDR": "Germany",
  "GEO": "Georgia",
  "GEQ": "Equatorial Guinea",
  "GER": "Germany",
  "GHA": "Ghana",
  "GRE": "Greece",
  "GRN": "Grenada",
  "GUA": "Guatemala",
  "GUI": "Guinea",
  "GUM": "Guam",
  "GUY": "Guyana",
  "HAI": "Haiti",
  "HKG": "China",
  "HON": "Honduras",
  "HUN": "Hungary",
  "INA": "Indonesia",
  "IND": "India",
  "IOA": "Individual Olympic Athletes",
  "IRI": "Iran",
  "IRL": "Ireland",
  "IRQ": "Iraq",
  "ISL": "Iceland",
  "ISR": "Israel",
  "ISV": "Virgin Islands, US",
  "ITA": "Italy",
  "IVB": "Virgin Islands, British",
  "JAM": "Jamaica",
  "JOR": "Jordan",
  "JPN": "Japan",
  "KAZ": "Kazakhstan",
  "KEN": "Kenya",
  "KGZ": "Kyrgyzstan",
  "KIR": "Kiribati",
  "KOR": "South Korea",
  "KOS": "Kosovo",
  "KSA": "Saudi Arabia",
  "KUW": "Kuwait",
  "LAO": "Laos",
  "LAT": "Latvia",
  "LBA": "Libya",
  "LBR": "Liberia",
  "LCA": "Saint Lucia",
  "LES": "Lesotho",
  "LIB": "Lebanon",
  "LIE": "Liechtenstein",
  "LTU": "Lithuania",
  "LUX": "Luxembourg",
  "MAD": "Madagascar",
  "MAL": "Malaysia",
  "MAR": "Morocco",
  "MAS": "Malaysia",
  "MAW": "Malawi",
  "MDA": "Moldova",
  "MDV": "Maldives",
  "MEX": "Mexico",
  "MGL": "Mongolia",
  "MHL": "Marshall Islands",
  "MKD": "Macedonia",
  "MLI": "Mali",
  "MLT": "Malta",
  "MNE": "Montenegro",
  "MON": "Monaco",
  "MOZ": "Mozambique",
  "MRI": "Mauritius",
  "MTN": "Mauritania",
  "MYA": "Myanmar",
  "NAM": "Namibia",
  "NBO": "Malaysia",
  "NCA": "Nicaragua",
  "NED": "Netherlands",
  "NEP": "Nepal",
  "NFL": "Canada",
  "NGR": "Nigeria",
  "NIG": "Niger",
  "NOR": "Norway",
  "NRU": "Nauru",
  "NZL": "New Zealand",
  "OMA": "Oman",
  "PAK": "Pakistan",
  "PAN": "Panama",
  "PAR": "Paraguay",
  "PER": "Peru",
  "PHI": "Philippines",
  "PLE": "Palestine",
  "PLW": "Palau",
  "PNG": "Papua New Guinea",
  "POL": "Poland",
  "POR": "Portugal",
  "PRK": "North Korea",
  "PUR": "Puerto Rico",
  "QAT": "Qatar",
  "RHO": "Zimbabwe",
  "ROT": "NA",
  "ROU": "Romania",
  "RSA": "South Africa",
  "RUS": "Russia",
  "RWA": "Rwanda",
  "SAA": "Germany",
  "SAM": "Samoa",
  "SCG": "Serbia",
  "SEN": "Senegal",
  "SEY": "Seychelles",
  "SIN": "Singapore",
  "SKN": "Saint Kitts",
  "SLE": "Sierra Leone",
  "SLO": "Slovenia",
  "SMR": "San Marino",
  "SOL": "Solomon Islands",
  "SOM": "Somalia",
  "SRB": "Serbia",
  "SRI": "Sri Lanka",
  "SSD": "South Sudan",
  "STP": "Sao Tome and Principe",
  "SUD": "Sudan",
  "SUI": "Switzerland",
  "SUR": "Suriname",
  "SVK": "Slovakia",
  "SWE": "Sweden",
  "SWZ": "Swaziland",
  "SYR": "Syria",
  "TAN": "Tanzania",
  "TCH": "Czech Republic",
  "TGA": "Tonga",
  "THA": "Thailand",
  "TJK": "Tajikistan",
  "TKM": "Turkmenistan",
  "TLS": "Timor-Leste",
  "TOG": "Togo",
  "TPE": "Taiwan",
  "TTO": "Trinidad",
  "TUN": "Tunisia",
  "TUR": "Turkey",
  "TUV": "NA",
  "UAE": "United Arab Emirates",
  "UAR": "Syria",
  "UGA": "Uganda",
  "UKR": "Ukraine",
  "UNK": "NA",
  "URS": "Russia",
  "URU": "Uruguay",
  "USA": "USA",
  "UZB": "Uzbekistan",
  "VAN": "Vanuatu",
  "VEN": "Venezuela",
  "VIE": "Vietnam",
  "VIN": "Saint Vincent",
  "VNM": "Vietnam",
  "WIF": "Trinidad",
  "YAR": "Yemen",
  "YEM": "Yemen",
  "YMD": "Yemen",
  "YUG": "Serbia",
  "ZAM": "Zambia",
  "ZIM": "Zimbabwe"
};
